### ISSUE TITLE
[Question] Contract storage architecture

### ISSUE THREAD

**Issue by aaliakseyenka** [uport-project/ethr-did-registry#50] opened 2022-06-21 09:23 UTC
**Is your feature request related to a problem? Please describe.**
This is more a question about architecture decision on how data is stored in contract.

**Describe the solution you'd like**
If I understand it right, the contract uses events as storage for different manipulations with did. As a result we have to search through entire network to get block data and analyse for changes(https://github.com/decentralized-identity/ethr-did-resolver/blob/master/src/resolver.ts#L75). 
I might ask a nubby question, although wouldn't it be more sufficient to store actual data in the latest block? Ie. create proper mappings and save/extract when needed. In terms of speed that should be much better.

Appreciate any comments on that.

**Comment by mirceanis** [comment] 2022-06-21 09:52
Thanks for asking.
Yes, the contract uses events for storage. This is by design to reduce the cost of gas.

Storing the data in normal contract storage would be possible, but **much much more expensive**.
Each event has a pointer to the latest change for that DID, so you don't have to search through the entire network, you only need to search the logs of a few specific blocks.
If you want to speed up the process, it should be relatively easy to cache the list of events (see also https://github.com/decentralized-identity/ethr-did-resolver/issues/150)

Please close this if you think my answer is enough.

**Closed** 2022-06-21 10:05 UTC
